/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lru.LRU;

/**
 *
 * @author aomine
 */
public class LRUView extends javax.swing.JFrame {

    private LRU lru;
    private int columna;
    private int marcos;
    private int paginasProceso;

    /**
     * Creates new form LRUVie
     */
    public LRUView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnIngresarPaginas = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        tituloResultados = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        btnPaginasProcesos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 33, 33));
        jLabel1.setText("Algoritmo LRU");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        btnIngresarPaginas.setText("Ingresar Paginas");
        btnIngresarPaginas.setEnabled(false);
        btnIngresarPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPaginasActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente Pagina");
        btnSiguiente.setEnabled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        tituloResultados.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tituloResultados.setForeground(new java.awt.Color(33, 33, 33));
        tituloResultados.setText("Datos:");

        resultados.setEditable(false);
        resultados.setBackground(new java.awt.Color(245, 245, 245));
        resultados.setBorder(null);
        resultados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resultados.setForeground(new java.awt.Color(33, 33, 33));
        resultados.setToolTipText("");
        resultados.setCaretColor(new java.awt.Color(33, 33, 33));
        jScrollPane2.setViewportView(resultados);

        jButton2.setText("Marcos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPaginasProcesos.setText("Paginas del proceos");
        btnPaginasProcesos.setEnabled(false);
        btnPaginasProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginasProcesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(394, 394, 394))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(btnPaginasProcesos)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresarPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloResultados)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarPaginas)
                    .addComponent(btnSiguiente)
                    .addComponent(jButton2)
                    .addComponent(btnPaginasProcesos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tituloResultados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPaginasActionPerformed
        columna = 0;
        String respuesta = JOptionPane.showInputDialog(rootPane, "Ingrese las paginas");

        try {
            String[] paginasStr = respuesta.split(" ");
            Integer[] paginas = new Integer[paginasStr.length];

            for (int i = 0; i < paginas.length; i++) {
                paginas[i] = Integer.valueOf(paginasStr[i]);
            }

            lru = new LRU(marcos, paginasProceso);
            lru.setPaginasParaUsar(paginas);
            setTableHeader();
            setTableData();
            btnSiguiente.setEnabled(true);
            tituloResultados.setText("Datos");
            resultados.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Las pagias ingresadas no son validos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            System.err.println("Cerro el dialog");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarPaginasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        lru.accesoAPagina(columna);
        setTableData();

        resultados.setText(lru.getDatos());

        columna++;

        if (columna == lru.getCantidadDePaginasAAcceder()) {
            btnSiguiente.setEnabled(false);
            tituloResultados.setText("Resultados");
            resultados.setText(lru.toString());
        }

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String respuesta = JOptionPane.showInputDialog(rootPane, "Numero de marcos");

        try {
            marcos = Integer.parseInt(respuesta);
            btnPaginasProcesos.setEnabled(true);
            setTableModel();
            btnSiguiente.setEnabled(false);
            tituloResultados.setText("Datos");
            resultados.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Las pagias ingresadas no son validos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            System.err.println("Cerro el dialog");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPaginasProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginasProcesosActionPerformed
        String respuesta = JOptionPane.showInputDialog(rootPane, "Numero de marcos");

        try {
            paginasProceso = Integer.parseInt(respuesta);
            btnIngresarPaginas.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Las pagias ingresadas no son validos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            System.err.println("Cerro el dialog");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPaginasProcesosActionPerformed

    private void setTableModel() {
        Object[] columns = {" "};

        DefaultTableModel model = new DefaultTableModel(null, columns);

        table.setModel(model);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        table.setRowHeight(30);

        for (int i = 1; i <= marcos; i++) {
            model.addRow(new Object[]{"marco " + i});
        }
    }

    private void setTableHeader() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setColumnCount(0);

        model.addColumn(" ");
        for (Integer pagina : lru.getPaginasParaAcceder()) {
            model.addColumn(pagina);
        }
    }

    private void setTableData() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        model.setRowCount(0);

        int contador = 1;
        for (Integer[] filaMemoria : lru.getMemoria()) {
            Object[] fila = new Object[filaMemoria.length + 1];
            fila[0] = "Marco " + contador;
            for (int i = 1; i < fila.length; i++) {
                fila[i] = filaMemoria[i - 1];
            }
            model.addRow(fila);
            contador++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LRUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LRUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LRUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LRUView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LRUView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarPaginas;
    private javax.swing.JButton btnPaginasProcesos;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane resultados;
    private javax.swing.JTable table;
    private javax.swing.JLabel tituloResultados;
    // End of variables declaration//GEN-END:variables
}
